### ISSUE TITLE
Playtest #2 comment thread

### ISSUE THREAD

**Issue by garykac** [garykac/woven#2]
Comments here will be organized and folded into the playtest summary doc:
https://github.com/garykac/blockchain/blob/master/playtests/2018-05-22-playtest-2.md

**Comment by garykac** [comment]
For next playtest:
* Have a simple set of ~12 cards, with separate rows for basic, medium, and advanced spells so that the set of available spells isn't clogged with spells that are too hard in the early game.
* Fix the spells so that there are more 3-square matrix cards
* Ignore constraints on the matrix cards. Constraints can be added to advanced spell cards (if needed).

**Comment by garykac** [comment]
Suggestion from Sverre: Have the top 2 Matrix cards visible so that players can choose either one.

**Comment by blinks** [comment]
Charges: need a symbol for "spend a charge, get an effect", and then you open up space for charge manipulation, and you can get symmetry for elemental power (which are just four types of charges that you can increase each turn).

Then, "1d+W: pull an elemental charge. [spend a charge]: prevent 1 damage."

**Comment by blinks** [comment]
Also, then you can just have a pool of charge tokens, in four colors / symbols for the four elements. Only allowing one color is probably unnecessary, too.

(To avoid the token requirement, you could just use your matrix's symbols as those charge tokens, and you cover up the symbols when you use the "charge", and uncover them to recharge. That'd solve a lot of side problems here...)

**Comment by garykac** [comment]
Because of the amount of time it took to build up the ability to cast a spell from the shared queue, when someone sniped a spell that you were working on felt really bad because you usually needed to start over again.

Making spells cast faster (but have longer teardown) removes this.
